TASK_OPTION = {
	'GREEDY':1,
	'MINIMAX':2,
	'ALPHABETA':3,
	'COMPETE':4
}

NEXT_STATE_FILE_NAME = 'next_state.txt'
TRAV_MINIMAX_TITLE = 'Node,Depth,Value\n'
TRAV_ALPHABETA_TITLE = 'Node,Depth,Value,Alpha,Beta\n'
TRAVERSE_LOG_NAME = 'traverse_log.txt'
PLAYER_ID1 = 1
PLAYER_ID2 = 2
NOT_PRUNED = 0
PRUNED = 1

PLAYER_LIST = [PLAYER_ID1, PLAYER_ID2]

PLAYER_LABEL = {
    PLAYER_ID1:'B',
    PLAYER_ID2:'A'
}

PLUS_INFINITY = 10000000
MINUS_INFINITY = -10000000

PLUS_INFINITY_STRING = 'Infinity'
MINUS_INFINITY_STRING = '-Infinity'

MAX_NODE = 1
MIN_NODE = 2

NODE_TYPE_STR = {
    MAX_NODE:'-Infinity',
    MIN_NODE:'Infinity'
}
